### ISSUE TITLE
Regression of login & other methods related to Geonetwork API url

### ISSUE THREAD

**Issue by eblondel** [eblondel/geonapi#21]
Related to
* https://github.com/eblondel/geonapi/issues/16
* https://github.com/eblondel/geonapi/issues/20

**Comment by eblondel** [comment]
@wheintz @juliepierson can you please reinstall now and check your GN connection with geonapi. This should fix the issue

**Comment by juliepierson** [comment]
Thanks @eblondel , Indigeo is down at the moment but I will test as soon as it's running again.

**Comment by wheintz** [comment]
Hi @eblondel, I just reinstalled geonapi and tried the connection, but I still have the same error message :+1: 

`Location: /geonetwork/accessDenied.jsp/eng/service-not-allowed?referer=UNKNOWN&type=me`

and then  `Error in curl::curl_fetch_memory(url, handle = handle) : 
  Maximum (10) redirects followed`

**Comment by eblondel** [comment]
Can you make sure you are not running a cache of the previous package as it occurs sometimes in online Rstudio?

**Comment by wheintz** [comment]
Unfortunately, I always launch a "Restart R session" before executing the workflow ... This time I executed it twice, but it is still the same result "access denied" :-/

**Comment by juliepierson** [comment]
Hi @eblondel , I just tested with geonapi 0.5-3, it worked for me : "[geonapi][INFO] Successfully authenticated to GeoNetwork!"

**Comment by eblondel** [comment]
Thanks @juliepierson ! @wheintz i've tested on the remote Rserver you gave me, and it works!
